#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if [ -z "$(ps -ef | grep socket.php | grep -v grep)" ]
then
    client_result "Application socket.php is already stopped"
else
    kill `ps -ef | grep socket.php | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi

#if [ -z "$(ps -ef | grep testrubyserver.rb | grep -v grep)" ]
#then
#    client_result "Application testrubyserver.rb is already stopped"
#else
#    kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#fi

